# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Alirul.Aideo
PackageVersion: 0.9.10
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Alirull18/Aideo-Music-Player/releases/download/v0.9.10/Aideo_0.9.10_x64-setup.exe
  InstallerSha256: EB0DE44C154EBB28B15C9EB91E501C7E4910C25B29254F2D5E1E29493BE04CAC
ManifestType: installer
ManifestVersion: 1.12.0
