# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Alirul.Aideo
PackageVersion: 0.9.10
PackageLocale: en-US
Publisher: Alirul
PublisherUrl: https://github.com/Alirull18
PublisherSupportUrl: https://github.com/Alirull18
PrivacyUrl: https://github.com/Alirull18
Author: Alirul
PackageName: Aideo
PackageUrl: https://alirull18.github.io/Aideo-Music-Player/
License: GPL-3.0-or-later
LicenseUrl: https://github.com/Alirull18/Aideo-Music-Player/blob/main/LICENSE
Copyright: Copyright (c) 2026 Alirul
CopyrightUrl: https://github.com/Alirull18/Aideo-Music-Player/blob/main/LICENSE
ShortDescription: Modern, lightweight open-source desktop music player
Description: Aideo Music Player is a modern, lightweight Windows desktop audio player designed for music lovers and audiophiles who want studio-quality sound, bit-perfect WASAPI Exclusive playback, word-by-word karaoke lyrics, and an adaptive glassmorphism interface on Windows 10 and Windows 11. Whether you are playing local lossless files (FLAC, WAV, MP3, AAC, ALAC) on your PC or streaming from Webstream, Aideo gives you complete control over your music library.
Moniker: aideo
Tags:
- Music Player
- Rust
- Flac
- audio
- music
- audio-player
- audiophile
- wasapi
- lyrics
- karaoke
- equalizer
- eq
- autoeq
- dsp
- media-player
- sound
ReleaseNotes: https://github.com/Alirull18/Aideo-Music-Player/blob/main/docs/RELEASE_NOTES_v0.9.10.md
ReleaseNotesUrl: https://github.com/Alirull18/Aideo-Music-Player/blob/main/docs/RELEASE_NOTES_v0.9.10.md
ManifestType: defaultLocale
ManifestVersion: 1.12.0
